export const arxiv_category_groups = [
  {
    group_name: "Computer Science",
    archive_code: "cs",
    categories: [
      { arxiv_category_code: "cs.AI", display_name: "Artificial Intelligence" },
      { arxiv_category_code: "cs.AR", display_name: "Hardware Architecture" },
      { arxiv_category_code: "cs.CC", display_name: "Computational Complexity" },
      { arxiv_category_code: "cs.CE", display_name: "Computational Engineering, Finance, and Science" },
      { arxiv_category_code: "cs.CG", display_name: "Computational Geometry" },
      { arxiv_category_code: "cs.CL", display_name: "Computation and Language" },
      { arxiv_category_code: "cs.CR", display_name: "Cryptography and Security" },
      { arxiv_category_code: "cs.CV", display_name: "Computer Vision and Pattern Recognition" },
      { arxiv_category_code: "cs.CY", display_name: "Computers and Society" },
      { arxiv_category_code: "cs.DB", display_name: "Databases" },
      { arxiv_category_code: "cs.DC", display_name: "Distributed, Parallel, and Cluster Computing" },
      { arxiv_category_code: "cs.DL", display_name: "Digital Libraries" },
      { arxiv_category_code: "cs.DM", display_name: "Discrete Mathematics" },
      { arxiv_category_code: "cs.DS", display_name: "Data Structures and Algorithms" },
      { arxiv_category_code: "cs.ET", display_name: "Emerging Technologies" },
      { arxiv_category_code: "cs.FL", display_name: "Formal Languages and Automata Theory" },
      { arxiv_category_code: "cs.GL", display_name: "General Literature" },
      { arxiv_category_code: "cs.GR", display_name: "Graphics" },
      { arxiv_category_code: "cs.GT", display_name: "Computer Science and Game Theory" },
      { arxiv_category_code: "cs.HC", display_name: "Human-Computer Interaction" },
      { arxiv_category_code: "cs.IR", display_name: "Information Retrieval" },
      { arxiv_category_code: "cs.IT", display_name: "Information Theory" },
      { arxiv_category_code: "cs.LG", display_name: "Machine Learning" },
      { arxiv_category_code: "cs.LO", display_name: "Logic in Computer Science" },
      { arxiv_category_code: "cs.MA", display_name: "Multiagent Systems" },
      { arxiv_category_code: "cs.MM", display_name: "Multimedia" },
      { arxiv_category_code: "cs.MS", display_name: "Mathematical Software" },
      { arxiv_category_code: "cs.NA", display_name: "Numerical Analysis" },
      { arxiv_category_code: "cs.NE", display_name: "Neural and Evolutionary Computing" },
      { arxiv_category_code: "cs.NI", display_name: "Networking and Internet Architecture" },
      { arxiv_category_code: "cs.OH", display_name: "Other Computer Science" },
      { arxiv_category_code: "cs.OS", display_name: "Operating Systems" },
      { arxiv_category_code: "cs.PF", display_name: "Performance" },
      { arxiv_category_code: "cs.PL", display_name: "Programming Languages" },
      { arxiv_category_code: "cs.RO", display_name: "Robotics" },
      { arxiv_category_code: "cs.SC", display_name: "Symbolic Computation" },
      { arxiv_category_code: "cs.SD", display_name: "Sound" },
      { arxiv_category_code: "cs.SE", display_name: "Software Engineering" },
      { arxiv_category_code: "cs.SI", display_name: "Social and Information Networks" },
      { arxiv_category_code: "cs.SY", display_name: "Systems and Control" },
    ],
  },
  {
    group_name: "Economics",
    archive_code: "econ",
    categories: [
      { arxiv_category_code: "econ.EM", display_name: "Econometrics" },
      { arxiv_category_code: "econ.GN", display_name: "General Economics" },
      { arxiv_category_code: "econ.TH", display_name: "Theoretical Economics" },
    ],
  },
  {
    group_name: "Electrical Engineering and Systems Science",
    archive_code: "eess",
    categories: [
      { arxiv_category_code: "eess.AS", display_name: "Audio and Speech Processing" },
      { arxiv_category_code: "eess.IV", display_name: "Image and Video Processing" },
      { arxiv_category_code: "eess.SP", display_name: "Signal Processing" },
      { arxiv_category_code: "eess.SY", display_name: "Systems and Control" },
    ],
  },
  {
    group_name: "Mathematics",
    archive_code: "math",
    categories: [
      { arxiv_category_code: "math.AC", display_name: "Commutative Algebra" },
      { arxiv_category_code: "math.AG", display_name: "Algebraic Geometry" },
      { arxiv_category_code: "math.AP", display_name: "Analysis of PDEs" },
      { arxiv_category_code: "math.AT", display_name: "Algebraic Topology" },
      { arxiv_category_code: "math.CA", display_name: "Classical Analysis and ODEs" },
      { arxiv_category_code: "math.CO", display_name: "Combinatorics" },
      { arxiv_category_code: "math.CT", display_name: "Category Theory" },
      { arxiv_category_code: "math.CV", display_name: "Complex Variables" },
      { arxiv_category_code: "math.DG", display_name: "Differential Geometry" },
      { arxiv_category_code: "math.DS", display_name: "Dynamical Systems" },
      { arxiv_category_code: "math.FA", display_name: "Functional Analysis" },
      { arxiv_category_code: "math.GM", display_name: "General Mathematics" },
      { arxiv_category_code: "math.GN", display_name: "General Topology" },
      { arxiv_category_code: "math.GR", display_name: "Group Theory" },
      { arxiv_category_code: "math.GT", display_name: "Geometric Topology" },
      { arxiv_category_code: "math.HO", display_name: "History and Overview" },
      { arxiv_category_code: "math.IT", display_name: "Information Theory" },
      { arxiv_category_code: "math.KT", display_name: "K-Theory and Homology" },
      { arxiv_category_code: "math.LO", display_name: "Logic" },
      { arxiv_category_code: "math.MG", display_name: "Metric Geometry" },
      { arxiv_category_code: "math.MP", display_name: "Mathematical Physics" },
      { arxiv_category_code: "math.NA", display_name: "Numerical Analysis" },
      { arxiv_category_code: "math.NT", display_name: "Number Theory" },
      { arxiv_category_code: "math.OA", display_name: "Operator Algebras" },
      { arxiv_category_code: "math.OC", display_name: "Optimization and Control" },
      { arxiv_category_code: "math.PR", display_name: "Probability" },
      { arxiv_category_code: "math.QA", display_name: "Quantum Algebra" },
      { arxiv_category_code: "math.RA", display_name: "Rings and Algebras" },
      { arxiv_category_code: "math.RT", display_name: "Representation Theory" },
      { arxiv_category_code: "math.SG", display_name: "Symplectic Geometry" },
      { arxiv_category_code: "math.SP", display_name: "Spectral Theory" },
      { arxiv_category_code: "math.ST", display_name: "Statistics Theory" },
    ],
  },
  {
    group_name: "Astrophysics",
    archive_code: "astro-ph",
    categories: [
      { arxiv_category_code: "astro-ph.CO", display_name: "Cosmology and Nongalactic Astrophysics" },
      { arxiv_category_code: "astro-ph.EP", display_name: "Earth and Planetary Astrophysics" },
      { arxiv_category_code: "astro-ph.GA", display_name: "Astrophysics of Galaxies" },
      { arxiv_category_code: "astro-ph.HE", display_name: "High Energy Astrophysical Phenomena" },
      { arxiv_category_code: "astro-ph.IM", display_name: "Instrumentation and Methods for Astrophysics" },
      { arxiv_category_code: "astro-ph.SR", display_name: "Solar and Stellar Astrophysics" },
    ],
  },
  {
    group_name: "Condensed Matter",
    archive_code: "cond-mat",
    categories: [
      { arxiv_category_code: "cond-mat.dis-nn", display_name: "Disordered Systems and Neural Networks" },
      { arxiv_category_code: "cond-mat.mes-hall", display_name: "Mesoscale and Nanoscale Physics" },
      { arxiv_category_code: "cond-mat.mtrl-sci", display_name: "Materials Science" },
      { arxiv_category_code: "cond-mat.other", display_name: "Other Condensed Matter" },
      { arxiv_category_code: "cond-mat.quant-gas", display_name: "Quantum Gases" },
      { arxiv_category_code: "cond-mat.soft", display_name: "Soft Condensed Matter" },
      { arxiv_category_code: "cond-mat.stat-mech", display_name: "Statistical Mechanics" },
      { arxiv_category_code: "cond-mat.str-el", display_name: "Strongly Correlated Electrons" },
      { arxiv_category_code: "cond-mat.supr-con", display_name: "Superconductivity" },
    ],
  },
  {
    group_name: "General Relativity and Quantum Cosmology",
    archive_code: "gr-qc",
    categories: [
      { arxiv_category_code: "gr-qc", display_name: "General Relativity and Quantum Cosmology" },
    ],
  },
  {
    group_name: "High Energy Physics - Experiment",
    archive_code: "hep-ex",
    categories: [
      { arxiv_category_code: "hep-ex", display_name: "High Energy Physics - Experiment" },
    ],
  },
  {
    group_name: "High Energy Physics - Lattice",
    archive_code: "hep-lat",
    categories: [
      { arxiv_category_code: "hep-lat", display_name: "High Energy Physics - Lattice" },
    ],
  },
  {
    group_name: "High Energy Physics - Phenomenology",
    archive_code: "hep-ph",
    categories: [
      { arxiv_category_code: "hep-ph", display_name: "High Energy Physics - Phenomenology" },
    ],
  },
  {
    group_name: "High Energy Physics - Theory",
    archive_code: "hep-th",
    categories: [
      { arxiv_category_code: "hep-th", display_name: "High Energy Physics - Theory" },
    ],
  },
  {
    group_name: "Mathematical Physics",
    archive_code: "math-ph",
    categories: [
      { arxiv_category_code: "math-ph", display_name: "Mathematical Physics" },
    ],
  },
  {
    group_name: "Nonlinear Sciences",
    archive_code: "nlin",
    categories: [
      { arxiv_category_code: "nlin.AO", display_name: "Adaptation and Self-Organizing Systems" },
      { arxiv_category_code: "nlin.CD", display_name: "Chaotic Dynamics" },
      { arxiv_category_code: "nlin.CG", display_name: "Cellular Automata and Lattice Gases" },
      { arxiv_category_code: "nlin.PS", display_name: "Pattern Formation and Solitons" },
      { arxiv_category_code: "nlin.SI", display_name: "Exactly Solvable and Integrable Systems" },
    ],
  },
  {
    group_name: "Nuclear Experiment",
    archive_code: "nucl-ex",
    categories: [
      { arxiv_category_code: "nucl-ex", display_name: "Nuclear Experiment" },
    ],
  },
  {
    group_name: "Nuclear Theory",
    archive_code: "nucl-th",
    categories: [
      { arxiv_category_code: "nucl-th", display_name: "Nuclear Theory" },
    ],
  },
  {
    group_name: "Physics",
    archive_code: "physics",
    categories: [
      { arxiv_category_code: "physics.acc-ph", display_name: "Accelerator Physics" },
      { arxiv_category_code: "physics.ao-ph", display_name: "Atmospheric and Oceanic Physics" },
      { arxiv_category_code: "physics.app-ph", display_name: "Applied Physics" },
      { arxiv_category_code: "physics.atm-clus", display_name: "Atomic and Molecular Clusters" },
      { arxiv_category_code: "physics.atom-ph", display_name: "Atomic Physics" },
      { arxiv_category_code: "physics.bio-ph", display_name: "Biological Physics" },
      { arxiv_category_code: "physics.chem-ph", display_name: "Chemical Physics" },
      { arxiv_category_code: "physics.class-ph", display_name: "Classical Physics" },
      { arxiv_category_code: "physics.comp-ph", display_name: "Computational Physics" },
      { arxiv_category_code: "physics.data-an", display_name: "Data Analysis, Statistics and Probability" },
      { arxiv_category_code: "physics.ed-ph", display_name: "Physics Education" },
      { arxiv_category_code: "physics.flu-dyn", display_name: "Fluid Dynamics" },
      { arxiv_category_code: "physics.gen-ph", display_name: "General Physics" },
      { arxiv_category_code: "physics.geo-ph", display_name: "Geophysics" },
      { arxiv_category_code: "physics.hist-ph", display_name: "History and Philosophy of Physics" },
      { arxiv_category_code: "physics.ins-det", display_name: "Instrumentation and Detectors" },
      { arxiv_category_code: "physics.med-ph", display_name: "Medical Physics" },
      { arxiv_category_code: "physics.optics", display_name: "Optics" },
      { arxiv_category_code: "physics.plasm-ph", display_name: "Plasma Physics" },
      { arxiv_category_code: "physics.pop-ph", display_name: "Popular Physics" },
      { arxiv_category_code: "physics.soc-ph", display_name: "Physics and Society" },
      { arxiv_category_code: "physics.space-ph", display_name: "Space Physics" },
    ],
  },
  {
    group_name: "Quantum Physics",
    archive_code: "quant-ph",
    categories: [
      { arxiv_category_code: "quant-ph", display_name: "Quantum Physics" },
    ],
  },
  {
    group_name: "Quantitative Biology",
    archive_code: "q-bio",
    categories: [
      { arxiv_category_code: "q-bio.BM", display_name: "Biomolecules" },
      { arxiv_category_code: "q-bio.CB", display_name: "Cell Behavior" },
      { arxiv_category_code: "q-bio.GN", display_name: "Genomics" },
      { arxiv_category_code: "q-bio.MN", display_name: "Molecular Networks" },
      { arxiv_category_code: "q-bio.NC", display_name: "Neurons and Cognition" },
      { arxiv_category_code: "q-bio.OT", display_name: "Other Quantitative Biology" },
      { arxiv_category_code: "q-bio.PE", display_name: "Populations and Evolution" },
      { arxiv_category_code: "q-bio.QM", display_name: "Quantitative Methods" },
      { arxiv_category_code: "q-bio.SC", display_name: "Subcellular Processes" },
      { arxiv_category_code: "q-bio.TO", display_name: "Tissues and Organs" },
    ],
  },
  {
    group_name: "Quantitative Finance",
    archive_code: "q-fin",
    categories: [
      { arxiv_category_code: "q-fin.CP", display_name: "Computational Finance" },
      { arxiv_category_code: "q-fin.EC", display_name: "Economics" },
      { arxiv_category_code: "q-fin.GN", display_name: "General Finance" },
      { arxiv_category_code: "q-fin.MF", display_name: "Mathematical Finance" },
      { arxiv_category_code: "q-fin.PM", display_name: "Portfolio Management" },
      { arxiv_category_code: "q-fin.PR", display_name: "Pricing of Securities" },
      { arxiv_category_code: "q-fin.RM", display_name: "Risk Management" },
      { arxiv_category_code: "q-fin.ST", display_name: "Statistical Finance" },
      { arxiv_category_code: "q-fin.TR", display_name: "Trading and Market Microstructure" },
    ],
  },
  {
    group_name: "Statistics",
    archive_code: "stat",
    categories: [
      { arxiv_category_code: "stat.AP", display_name: "Applications" },
      { arxiv_category_code: "stat.CO", display_name: "Computation" },
      { arxiv_category_code: "stat.ME", display_name: "Methodology" },
      { arxiv_category_code: "stat.ML", display_name: "Machine Learning" },
      { arxiv_category_code: "stat.OT", display_name: "Other Statistics" },
      { arxiv_category_code: "stat.TH", display_name: "Statistics Theory" },
    ],
  },
];

export const arxiv_category_catalog = arxiv_category_groups.flatMap((category_group) => category_group.categories);

const display_name_by_code = new Map([
  ...arxiv_category_catalog.map((catalog_entry) => [catalog_entry.arxiv_category_code, catalog_entry.display_name]),
  ...arxiv_category_groups.map((category_group) => [category_group.archive_code, `All ${category_group.group_name} categories`]),
]);

export function display_name_for_arxiv_category_code(arxiv_category_code) {
  return display_name_by_code.get(arxiv_category_code) ?? arxiv_category_code;
}
